version: 0.0.1
apimServiceName: csquestions
apiVersionSets: #Optional
  - id: QuestionsApiVersionSet
    displayName: QuestionsApi
    description: An API for CloudSkills Questions
    versioningSchema: Query
    versionQueryName: versioningQuery
    versionHeaderName: versionHeader
apis:
  - name: Questions
    apiVersion: v1
    apiVersionDescription: version 1
    apiVersionSetId: QuestionsApiVersionSet
    revision: 1 # Optional
    revisionDescription: revision 1 # Optional
    openApiSpec: /Users/pieter/@blogs/repos/csQA/csQA/IaC/apim/swagger.json
    suffix: questions
    protocols: http
    products: starter
outputLocation: /Users/pieter/@blogs/repos/csQA/csQA/IaC/apim/templates
linked: true
linkedTemplatesBaseUrl: /Users/pieter/@blogs/repos/csQA/csQA/IaC/apim/apim.base.json
